apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    env: development
    project: dg-inventory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: dev
data:
  SERVER_NAME: "inventory.example.com" # Kustomize will replace this
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  namespace: dev
type: Opaque
stringData:
  # Redis Password (Keep it strong for Prod)
  REDIS_PASSWORD: "redis-password"
  
  # MongoDB Credentials
  MONGO_ROOT_USER: "admin"
  MONGO_ROOT_PASSWORD: "password"  

  # MongoDB Connection String
  # We use the full URI you provided
  MONGO_URI: "mongodb uri"
