apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: inventory-gateway
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "inventory.example.com" #  Kustomize will replace this
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "inventory.example.com"  # Kustomize will replace this
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: inventory-app-tls-secret
      allowedRoutes:
        namespaces:
          from: Same
---
# ROUTE 1: The Secure App Route (HTTPS)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inventory-app-route
  namespace: dev
spec:
  parentRefs:
    - name: inventory-gateway
      namespace: dev
      sectionName: https
  hostnames:
    - "inventory.example.com"  # Kustomize will replace this
  rules:
    - backendRefs:
        - name: frontend
          port: 80
---
# ROUTE 2: The Redirect Route (HTTP)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  namespace: dev
spec:
  parentRefs:
    - name: inventory-gateway
      namespace: dev
      sectionName: http
  hostnames:
    - "inventory.example.com"  # Kustomize will replace this
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301 # Permanent Redirect