name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- STAGE 1: Testing ---
  test-auth:
    name: Test Auth Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './auth/package-lock.json'

      - name: Install & Run Tests
        run: |
          cd auth
          npm install
          npm test

  test-backend:
    name: Test Backend Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install & Run Tests
        run: |
          cd backend
          npm install
          npm test

  # --- STAGE 2: Docker Build ---
  docker:
    name: Containarization
    needs: [test-auth, test-backend] # ONLY runs if both test jobs pass
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    
        
      # --- Build Auth Image ---
      - name: Build Auth Service
        uses: docker/build-push-action@v6
        with:
          context: ./auth
          #load: true # Pushes the image to the local Docker daemon
          tags: ${{ vars.DOCKERHUB_USERNAME }}/inventory-auth:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

      # --- Build Backend Image ---
      - name: Build Backend Service
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          #load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/inventory-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

      # --- Build Frontend Image ---
      - name: Build Frontend Service
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          #load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/inventory-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

      - name: Clean up unused Docker data
        run: docker image prune -f    

  # --- STAGE 3: k8s dev deployment ---
  deploy:
    name: DEV_Deployment
    needs: docker   # ONLY runs if image build successfull
    runs-on: [self-hosted, dev]
    environment: DEV  # For accessing "DEV" env & secret
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}  

      - name: Inject env & Secrets into Kustomize
        run: |
         # Using '|' as a delimiter to handle the slashes in MONGO_URI

         sed -i "s|__SERVER_NAME__|${{ env.SERVER_NAME }}|g" k8s/dev/kustomization.yaml

         sed -i "s|__REDIS_PASSWORD__|${{ secrets.REDIS_PASSWORD }}|g" k8s/dev/kustomization.yaml
         sed -i "s|__MONGO_ROOT_USER__|${{ secrets.MONGO_ROOT_USER }}|g" k8s/dev/kustomization.yaml
         sed -i "s|__MONGO_ROOT_PASSWORD__|${{ secrets.MONGO_ROOT_PASSWORD }}|g" k8s/dev/kustomization.yaml
         sed -i "s|__MONGO_URI__|${{ secrets.MONGO_URI }}|g" k8s/dev/kustomization.yaml  
    
      - name: Deploy to Kubernetes
        run: |
         kustomize edit set image kabbo06/inventory-auth=${{ vars.DOCKERHUB_USERNAME }}/inventory-auth:${{ github.sha }}
         kustomize edit set image kabbo06/inventory-backend=${{ vars.DOCKERHUB_USERNAME }}/inventory-backend:${{ github.sha }}
         kustomize edit set image kabbo06/inventory-frontend=${{ vars.DOCKERHUB_USERNAME }}/inventory-frontend:${{ github.sha }}
    
         kubectl apply -k k8s/dev   
    