name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- STAGE 1: Testing ---
  test-auth:
    name: Test Auth Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './auth/package-lock.json'

      - name: Install & Run Tests
        run: |
          cd auth
          npm install
          npm test

  test-backend:
    name: Test Backend Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install & Run Tests
        run: |
          cd backend
          npm install
          npm test

  # --- STAGE 2: Docker Build ---
  docker:
    name: Containarization & Image Push
    needs: [test-auth, test-backend] # ONLY runs if both test jobs pass
    runs-on: [self-hosted, dev]

    strategy:
      matrix:
        service:
          - name: auth
            context: ./auth
            image: inventory-auth
          - name: backend
            context: ./backend
            image: inventory-backend
          - name: frontend
            context: ./frontend
            image: inventory-frontend 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.service.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.service.image }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          #load: true
          push: true

      - name: Clean up unused Docker data
        run: docker image prune -f    

  # --- STAGE 3: k8s DEV Deployment ---
  dev-deploy:
    name: DEV Deployment
    needs: docker   # ONLY runs if image build successfull
    runs-on: [self-hosted, dev]
    environment: DEV  # For accessing "DEV" env & secret
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}  

      - name: Inject ENV & Secrets into Kustomize
        run: |
         # 1. Escape ampersands (&) and special char for the sed command
          ESCAPED_MONGO_URI=$(echo "${{ secrets.MONGO_URI }}" | sed 's/&/\\&/g')
          ESCAPED_MONGO_ROOT_PASSWORD=$(echo "${{ secrets.MONGO_ROOT_PASSWORD }}" | sed 's/|/\\|/g')
          
          # 2. Inject values using '|' as a delimiter
          sed -i "s|__MONGO_URI__|$ESCAPED_MONGO_URI|g" k8s/dev/kustomization.yaml
          sed -i "s|__MONGO_ROOT_PASSWORD__|$ESCAPED_MONGO_ROOT_PASSWORD|g" k8s/dev/kustomization.yaml

          sed -i "s|__SERVER_NAME__|${{ vars.SERVER_NAME }}|g" k8s/dev/kustomization.yaml
          sed -i "s|__REDIS_PASSWORD__|${{ secrets.REDIS_PASSWORD }}|g" k8s/dev/kustomization.yaml
          sed -i "s|__MONGO_ROOT_USER__|${{ secrets.MONGO_ROOT_USER }}|g" k8s/dev/kustomization.yaml
      
      - name: Deploy to Kubernetes dev Cluster
        run: |
         cd k8s/dev
         
         kustomize edit set image kabbo06/inventory-auth=${{ vars.DOCKERHUB_USERNAME }}/inventory-auth:${{ github.sha }}
         kustomize edit set image kabbo06/inventory-backend=${{ vars.DOCKERHUB_USERNAME }}/inventory-backend:${{ github.sha }}
         kustomize edit set image kabbo06/inventory-frontend=${{ vars.DOCKERHUB_USERNAME }}/inventory-frontend:${{ github.sha }}
    
         kubectl apply -k . 

  # --- STAGE 4: k8s DEV Integration-Testing ---
  dev-integration-testing:
    name: Dev Integration Testing
    needs: dev-deploy 
    uses: ./.github/workflows/reusable-health-check.yml
    with:
      environment: DEV

  # --- STAGE 5: k8s PROD Deployment ---
  prod-deploy:
    name: PROD Deployment
    needs: dev-integration-testing
    runs-on: [self-hosted, dev]
    environment: PROD  # For accessing "PROD" env & secret
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}  

      - name: Inject ENV & Secrets into Kustomize
        run: |
          # 1. Escape ampersands for PROD Atlas URI
          ESCAPED_MONGO_URI=$(echo "${{ secrets.MONGO_URI }}" | sed 's/&/\\&/g')

          # 2. Inject values using '|' as a delimiter
          sed -i "s|__MONGO_URI__|$ESCAPED_MONGO_URI|g" k8s/prod/kustomization.yaml
          sed -i "s|__SERVER_NAME__|${{ vars.SERVER_NAME }}|g" k8s/prod/kustomization.yaml
          sed -i "s|__REDIS_PASSWORD__|${{ secrets.REDIS_PASSWORD }}|g" k8s/prod/kustomization.yaml 
      
      - name: Deploy to Kubernetes prod Cluster
        run: |
         cd k8s/prod
         
         kustomize edit set image kabbo06/inventory-auth=${{ vars.DOCKERHUB_USERNAME }}/inventory-auth:${{ github.sha }}
         kustomize edit set image kabbo06/inventory-backend=${{ vars.DOCKERHUB_USERNAME }}/inventory-backend:${{ github.sha }}
         kustomize edit set image kabbo06/inventory-frontend=${{ vars.DOCKERHUB_USERNAME }}/inventory-frontend:${{ github.sha }}

         kustomize edit set replicas auth=${{ vars.REPLICAS }}
         kustomize edit set replicas backend=${{ vars.REPLICAS }}
         kustomize edit set replicas frontend=${{ vars.REPLICAS }}
    
         kubectl apply -k . 

  # --- STAGE 6: k8s PROD Integration-Testing ---
  prod-integration-testing:
    name: PROD Integration Testing
    needs: prod-deploy
    uses: ./.github/workflows/reusable-health-check.yml
    with:
      environment: PROD
       
  # --- STAGE 7: Undo PROD Deployments if Fails---   
  prod-rollback:
    name: PROD Rollback
    needs: prod-integration-testing
    if: failure()
    runs-on: [self-hosted, dev]
    environment: PROD

    steps:
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Rollback Auth Deployment
        run: kubectl rollout undo deployment/auth

      - name: Rollback Backend Deployment
        run: kubectl rollout undo deployment/backend

      - name: Rollback Frontend Deployment
        run: kubectl rollout undo deployment/frontend     