name: Simple Runner Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Echo Hello World
        run: echo " The self-hosted runner is active and working."
      - name: List file
        run: ls -l
      - name: Read file
        run: cat README.md

      

          
