name: Simple Runner Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: [self-hosted, dev]
    steps:
      - name: Echo Hello World
        run: echo "Hi The self-hosted runner is active and working."

          
